Added resolution info to system.sav-offsets.md
Made-in-Abyss-Modding-Community/Modding-Reference pull request #18
Opened 2022-11-07 18:06 UTC by Urocu

2022-11-08 01:07 UTC, drunken-hearted requested changes
spelling mistake, all Resoluton --> Resolution

2022-11-08 14:44 UTC, Urocu commented
Fixed it

2022-11-08 15:34 UTC, drunken-hearted approved these changes

2023-02-23 20:12 UTC, PioBlastic approved these changes

2023-02-23 20:12 UTC, merged